import { React } from "react";

import Head from "next/head";

export default function Home() {
	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

<<<<<<< HEAD
			<main>
				<h1>Welcome to chrono</h1>
=======
      <main>
        <h1>Welcome to chrono</h1>
>>>>>>> 0e12d71e892686bfd419605a5444f72aa3d761b4

				<p>
					Get started by editing <code>pages/index.js</code>
				</p>

				<h2 className="font-mono py-10 font-semibold text-green-500">
					Chrono Project Intiation Sequence . . . <br />
					Warping to nearest Intersetller Void in . . . 3 . . .2 . . 1
				</h2>
			</main>
		</div>
	);
}
