import { React } from "react";

import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>
          Welcome to chrono
        </h1>

        <p>
          Get started by editing <code>pages/index.js</code>
        </p>
      </main>
    </div>
  );
}
