import React from "react";

import Link from "next/link";
import Head from "next/head";
import Index from "../components/HomePage/Index";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="my-4">
        <Link href="/designsystem">
          <a className="py-2 px-4 bg-gradient-right-bottom text-white rounded ml-2 hover:shadow-md transition-all duration-250">
            Go to Design System{" "}
          </a>
        </Link>
      </div>

      <Index></Index>
    </div>
  );
}
